src/ProjectBundle/Form/PutUserForm.php
<?php

namespace ProjectBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class PutUserForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'firstName',
            'text',
            array(
                'label' => 'Имя',
                'constraints' => array(
                   // new NotBlank(),
                    new Length(
                        array(
                            'max' => 255,
                            'maxMessage' => 'Максимальная длина - 255 символа'
                        ))
                ),
            )
        );

        $builder->add(
            'lastName',
            'text',
            array(
                'label' => 'Фамилия',
                'constraints' => array(
                   // new NotBlank(),
                    new Length(
                        array(
                            'max' => 255,
                            'maxMessage' => 'Максимальная длина - 255 символа'
                        ))
                ),
            )
        );

        $builder->add(
            'submit',
            'submit',
            array(
                'label' => 'Отправить',
                'attr' => array(
                    'class' => 'submit'
                )
            )
        );
    }

    public function getName()
    {
        return 'User';
    }

}

src/ProjectBundle/Resources/views/Index/index.html.twig
{% extends "ProjectBundle::layout.html.twig" %}

{% block body %}

    {% for flash_message in app.session.flashbag.get('notice') %}
        <div class="flash-notice">
            {{ flash_message }}
        </div>
    {% endfor %}

    <div class="overPanel">
        <span>{{ currentUser.username }}</span>
        <a href="{{ path('put_user') }}">Изменить профиль</a>
        <a href="{{ path('stocks') }}">Мой портфель</a>
    </div>

    <div class="row">
        <div class="col-md-6 col-md-offset-2">
            {% for comment in comments %}
                <div class="author">{{ comment.user.username }}</div>
                <div class="comment">
                    {% if currentUser.id == comment.user.id %}
                        <p class="change" data-id="{{ comment.id }}" data-change="true">{{ comment.message }}</p>
                    {% else %}
                        <p class="change" data-id="{{ comment.id }}">{{ comment.message }}</p>
                    {% endif %}
                    <a class="save" data-id="{{ comment.id }}">сохранить</a>
                </div>
            {% endfor %}
            <a class="btn btn-primary showNewComment">Новый комментарий</a>
            <div class="newComment"></div>
        </div>
        <div class="col-md-4">
            {% if friends is defined %}
                {% for friend in friends %}
                    <img src="{{ friend.picture.url }}">
                    <p>{{ friend.name }}</p>
                {% endfor %}
            {% endif %}
        </div>
    </div>

    {% raw %}
        <script id="theTmpl" type="text/x-jsrender">
            <textarea class="newMessage">{{:message}}</textarea>
        </script>

        <script id="theTmpl1" type="text/x-jsrender">
            <p class="change" data-id="{{:id}}">{{:message}}</p>
        </script>
    {% endraw %}

    <script>
        $(document).ready(function () {
            var changeStatus = false;
            var createStatus = false;
            var element;

            function change(element, data) {
                var template = $.templates("#theTmpl");
                template.link($(element), data);
                changeStatus = true;
                $('.save*[data-id="' + data.id + '"]').css('display', 'block');
            };

            $(".change").click(function () {
                if (changeStatus !== true && $(this).attr('data-change') == "true") {
                    var message = $(this).text();
                    id = $(this).attr('data-id');
                    element = $(this);

                    $.ajax({
                        url: Routing.generate('get_comment', {'id': id}),
                        type: "GET",
                        dataType: 'json'
                    }).done(function (result) {
                        change(element, JSON.parse(result.comment));
                    });
                }
            });

            $(".save").click(function () {
                id = $(this).attr('data-id');
                var data =
                {
                    "message": $(".newMessage").val(),
                    "id": id
                };

                $.ajax({
                    url: Routing.generate('put_comment', {'id': id}),
                    type: "POST",
                    data: {'message': data.message},
                    dataType: 'json'
                }).done(function (result) {
                    changeStatus = false;
                });

                $(this).css('display', 'none')
                var template = $.templates("#theTmpl1");
                template.link($(element), data);
                element = false;
            });

            $(".showNewComment").click(function () {
                if(createStatus === false){
                    createStatus = true;
                    $.ajax({
                        url: Routing.generate('create_comment'),
                        type: "GET",
                        dataType: 'html'
                    }).done(function (result) {
                        $(".newComment").append(result);
                    });
                }
            });
        });
    </script>
{% endblock %}